name: CI
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8==3.9.2 flake8-bugbear flake8-comprehensions isort==5.8.0
          python -m pip install black==21.6b0
          flake8 --version
      - name: Lint
        run: |
          echo "Running isort"
          isort --profile black .
          echo "Running black"
          black --check .
          echo "Running flake8"
          flake8 .
